### ISSUE TITLE
Applicazione Docker Flask MongoDB NGINX

### ISSUE THREAD

**Issue by cicognani1971** [serenasensini/Docker-Apogeo#1]
Buonasera Serena
ho acquistato su Amazon il suo ottimo libro.
Ho avviato correttamente i container con docker-compose up; vedo NGINX in ascolto sulla porta 80, ma ogni volta che gli invio comandi curl ottengo nel log del web server dei codici 404. Potrebbe ricontrollare il codice Python/Flask?
Grazie

**Comment by serenasensini** [comment]
Ciao! 

Grazie mille per il feedback. In effetti, il Dockerfile di Nginx aveva diversi problemi, ma quello principale era dovuto al fatto che il file di configurazione importato non andava a sovrascrivere quello di default. Ho aggiornato il repository con l'esempio funzionante (vedi foto) e ho snellito notelvolmente il Dockerfile, utilizzando l'immagine di base del repository di _nginx_!

A presto,

![immagine](https://user-images.githubusercontent.com/17291035/147417031-0de606ec-904a-4fee-9728-c2188eca0120.png)
