### ISSUE TITLE
Problemi con applicazione Laravel, nginx e MySQL

### ISSUE THREAD

**Issue by Rita-web** [serenasensini/Docker-Apogeo#2]
Gent.ma Serena, ho poi risolto da me la questione in oggetto che volevo porle. 
Intanto provo gli altri esempi pratici da lei proposti nel suo libro :-)

**Comment by serenasensini** [comment]
Ciao Rita! Hai risolto? :)

**Comment by Rita-web** [comment]
Ciao Serena, purtroppo non ci sono ancora con l'esempio
Laravel-nginx-MySQL, dato che non riesco a vedere la pagina di Laravel.
Il localhost mi dà il seguente errore:
Fatal error: Composer detected issues in your platform: Your Composer
dependencies require a PHP version ">= 8.0.2". You are running 7.2.34. in
/var/www/vendor/composer/platform_check.php on line 24

Ho provato anche qualcun altro degli esempi pratici che hai fornito nel
libro.
L'applicazione Flask con SQLite e pure Flask con MongoDB mi si bloccano,
dopo il lancio del comando 'docker-compose up -d', *waiting for connections
on port 27017*: ho atteso almeno 40 minuti, ho quindi rinunciato con un
doppio ctrl^C.
Mi spiace tanto disturbarti per chiedere aiuto!



Il giorno lun 31 gen 2022 alle ore 14:11 Serena Sensini <
***@***.***> ha scritto:
